### ISSUE TITLE
'make' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by WillowTough** [potsbo/any-ticker#30]
A classic error. I'm really sorry if this is annoying but everything i've tried to solve this hasn't worked and you somehow got it to work so i am asking here what the problem is. I ran the command and got:
`C:\Users\jago>git clone https://github.com/potsbo/any-ticker.git && cd any-ticker && make
Cloning into 'any-ticker'...
remote: Enumerating objects: 1225, done.
Rremote: Total 1225 (delta 0), reused 0 (delta 0), pack-reused 1225    ving objects:  96% (1176/1225), 1.
Receiving objects: 100% (1225/1225), 1.28 MiB | 2.12 MiB/s, done.
Resolving deltas: 100% (703/703), done.
'make' is not recognized as an internal or external command,
operable program or batch file.`

I'm sorry again thank you in advance

**Comment by potsbo** [comment]
Thank you for trying to use my code! I'm so glad to see someone is interested in this project.

This is the expected behavior in my laptop (macOS).
```
:) % git clone https://github.com/potsbo/any-ticker.git && cd any-ticker && make                                                                                                                                                                                                                                                                                                                                                                                                          21-01-21 12:00:18
Cloning into 'any-ticker'...
remote: Enumerating objects: 1225, done.
remote: Total 1225 (delta 0), reused 0 (delta 0), pack-reused 1225
Receiving objects: 100% (1225/1225), 1.28 MiB | 1.35 MiB/s, done.
Resolving deltas: 100% (703/703), done.
LICENSE             any-ticker.cpp      coordinate.cpp      file_convert.cpp    fonts/              life_object.cpp     main.cpp            objects/            rleto106.h          stdafx.h            test.sh*            ticker_message.h    typeset.h
README.md           any-ticker.h        coordinate.h        file_convert.h      lib/                life_object.h       makefile            rleto106.cpp        set_parameters.cpp  test/               ticker_message.cpp  typeset.cpp
g++ -std=c++11   -c -o main.o main.cpp
g++ -std=c++11   -c -o any-ticker.o any-ticker.cpp
g++ -std=c++11   -c -o typeset.o typeset.cpp
g++ -std=c++11   -c -o set_parameters.o set_parameters.cpp
g++ -std=c++11   -c -o file_convert.o file_convert.cpp
g++ -std=c++11   -c -o rleto106.o rleto106.cpp
g++ -std=c++11   -c -o life_object.o life_object.cpp
g++ -std=c++11   -c -o ticker_message.o ticker_message.cpp
g++ -std=c++11   -c -o coordinate.o coordinate.cpp
g++ -o life main.o any-ticker.o typeset.o set_parameters.o file_convert.o rleto106.o life_object.o ticker_message.o coordinate.o
```
By seeing your error message, I believe this is because of the lacking `make` command which is a widely used fundamental build tool.
Also, your prompt indicates you are using a Windows machine, is it correct?
If so, finding a way to use `make` in Windows can help this.
The bad news is I'm not familiar with that OS. But I believe many people around the world want the tool run in the environment, so it won't be so hard to find some article to make it possible.

Something like
- https://stackoverflow.com/questions/2532234/how-to-run-a-makefile-in-windows
- https://superuser.com/questions/363359/how-to-use-makefiles-on-windows

Or start using Linux or macOS is another option, which shouldn't be too hard but can easily avoid these platform issues.

**Comment by ManginPlay** [comment]
You can use wsl on windows 10 to compile the program. I only managed to do it with epicTCK 's fork. I installed git, autoconf, gcc and g++ and it compiled.
